### ISSUE TITLE
download not working

### ISSUE THREAD

**Issue by Puginator9000** [KingOfMiners/Extended-Planets#1]
so as you read above you know that i can't download i dont know if this is an error or there is a new download link                                but i simply go on this link          https://forum.micdoodle8.com/index.php?threads/1-7-10-extendedplanets-alpha.6531/ 
and press on download and this pops out
![screenshot_2](https://user-images.githubusercontent.com/44668327/47950255-5d494880-df58-11e8-9875-756fa2039670.png)

**Comment by Puginator9000** [comment]
please tell me if this is an error or there is a new download link

**Comment by KingOfMiners** [comment]
Do you have access to dropbox? Is it being blocked?
